name: CI/CD Pipeline for a Node.js Application

on:
  push:
    branches:
      - main
jobs:
    test:
      runs-on: self-hosted
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 20

        - name: Install Dependencies
          run: npm install
        
        - name: Run Tests
          run: |
            npm run check > test-results.txt

        - name: Upload test result
          uses: actions/upload-artifact@v3
          with:
            name: test-results
            path: test-results.txt

    deploy:
      needs: test
      runs-on: self-hosted
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Download Test Results
          uses: actions/download-artifact@v3
          with:
            name: test-results
            path: .

        - name: Display Test Results
          run: type test-results.txt

        - name: Install Dependencies
          run: npm install

        - name: Deploy with PM2
          run: |
            pm2 stop app || exit 0
            pm2 start index.js --name app

        - name: Deployment Done
          run: |
            echo "Deployent Done"
  



